---
resources:
  - name: check-changes-to-master-branch
    type: git
    icon: github-circle
    source:
      uri: https://github.com/Smarsh/cf-kafka-boshrelease
      branch: master

jobs:
  - name: authenticate-to-bosh
    public: true
    plan:
      - get: check-changes-to-master-branch
        trigger: true
      - task: configure-bosh-and-repo
        config:
          inputs:
            - name: check-changes-to-master-branch
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: bosh/cli2 }
          params:
            BOSH_ENVIRONMENT: ((DIR_IP))
            BOSH_CLIENT: ((BOSH_CLIENT))
            BOSH_CLIENT_SECRET: ((BOSH_SECRET))
            BOSH_CA_CERT: ((BOSH_CA_CERT))
            BOSH_JUMPBOX_KEY: ((BOSH_JUMPBOX_KEY))
            GITHUB_USER: ((GITHUB_USER))
            GITHUB_PRIV_KEY: ((GITHUB_PRIV_KEY))
            GITHUB_REPO: ((GITHUB_REPO))
          run:
            path: sh
            args:
            - -exc
            - |
              echo "Configuring files and directories"
              echo "----"
              apt-get install git -f -y > /dev/null
              mkdir ~/.ssh
              echo "$GITHUB_PRIV_KEY" > ~/.ssh/id_rsa
              git clone $GITHUB_REPO
              export GITHUB_DIR=`echo $GITHUB_REPO | cut -d / -f 5`
              echo "$BOSH_JUMPBOX_KEY" > jumpbox.key
              echo "$BOSH_CA_CERT" > ca_cert.crt
            
              echo "Configuring BOSH environment"
              bosh alias-env $BOSH_ENVIRONMENT -e $BOSH_ENVIRONMENT --ca-cert ${PWD}/ca_cert.crt
              export BOSH_CLIENT=david.middleton@smarsh.com
              export BOSH_ALL_PROXY=ssh+socks5://jumpbox@${BOSH_ENVIRONMENT}:22?private-key=${PWD}/jumpbox.key
              
              cd $GITHUB_DIR    

              echo "Cutting the release"
              bosh create-release --force  --version=2.4.1-1

              ## Waiting on S3 bucket for these steps
              #mkdir             
              #cat <<EOF > config/final.yml
              #---
              #name: kafka
              #blobstore:
              #  provider: local
              #  options:
              #    blobstore_path:
              #      .dev-kafka-blobstore
              #EOF
