---
resources:
  - name: check-changes-to-master-branch
    type: git
    icon: github-circle
    source:
      uri: https://github.com/dpmidd/PentestNotes.git
      branch: master

jobs:
  - name: master-branch-changed
    public: true
    plan:
      - get: check-changes-to-master-branch
        trigger: true
      - task: list-files
        config:
          inputs:
            - name: check-changes-to-master-branch
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: bosh/cli2 }
          params:
            BOSH_ENVIRONMENT: ((DIR_IP))
            BOSH_CLIENT: ((BOSH_CLIENT))
            BOSH_CLIENT_SECRET: ((BOSH_SECRET))
            BOSH_CA_CERT: ((BOSH_CA_CERT))
            BOSH_JUMPBOX_KEY: ((BOSH_JUMPBOX_KEY))
          run:
            path: sh
            args:
            - -exc
            - |
              echo "$BOSH_JUMPBOX_KEY" > jumpbox.key
              echo "$BOSH_CA_CERT" > ca_cert.crt
              bosh alias-env $BOSH_ENVIRONMENT -e $BOSH_ENVIRONMENT --ca-cert ${PWD}/ca_cert.crt
              export BOSH_CLIENT=david.middleton@smarsh.com
              export BOSH_ALL_PROXY=ssh+socks5://jumpbox@${BOSH_ENVIRONMENT}:22?private-key=${PWD}/jumpbox.key
              bosh deployments
