---
resources:
  - name: check-changes-to-master-branch
    type: git
    icon: github-circle
    source:
      uri: https://github.com/dpmidd/PentestNotes.git
      branch: master

jobs:
  - name: master-branch-changed
    public: true
    plan:
      - get: concourse-docs-git
        trigger: true
      - task: list-files
        config:
          inputs:
            - name: concourse-docs-git
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: ls
            args: ["-la", "./concourse-docs-git"]
