---
anchors:
  blobstore_credentials: &blobstore_credentials
    AWS_ACCESS_KEY_ID: ((aws-access-key-id))
    AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
  smarsh_releases_bucket: &smarsh_releases_bucket
    bucket: smarsh-bosh-releases
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))

resources:
  - name: kafka-repo
    type: git
    icon: github-circle
    source:
      uri: https://github.com/Smarsh/cf-kafka-boshrelease
      branch: pipeline

jobs:
  - name: cut-release
    public: true
    plan:
      - get: kafka-repo
        trigger: true

      - task: create_final_release
        file: kafka-repo/ci/tasks/create_final_release.yml
        params: 
#          << : *blobstore_credentials
          << : *smarsh_releases_bucket
          BOSH_ENVIRONMENT: ((DIR_IP))
          BOSH_CLIENT: ((BOSH_CLIENT))
          BOSH_CLIENT_SECRET: ((BOSH_SECRET))
          BOSH_CA_CERT: ((BOSH_CA_CERT))
          BOSH_JUMPBOX_KEY: ((BOSH_JUMPBOX_KEY))
          GITHUB_USER: ((GITHUB_USER))
          GITHUB_PRIV_KEY: ((GITHUB_PRIV_KEY))
          GITHUB_REPO: ((GITHUB_REPO))
